# Site settings
title: RENO - STAV SK s.r.o.
description: "Stavebná Firma"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reno-stav.github.io/" # the name of your domain
logo_url: svg/min/logo.svg

# Contact info
contact:
    phone: '0905 372 058'
    email: 'd.lieskovsky@gmail.com'
    address: Nitra Slovakia

testimonials:
    testimonials_img: parallax.jpg

copyright: © 2018 RENO - STAV SK s.r.o. - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
